# standard jekyll configuration

permalink: /:year/:month/:day/:title/
pygments:  true
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock']

title: Neatline Documentation
domain: http://docs.neatline.org
